import React from 'react'
import about_img from '../appImages/about_us.jpg'
const About = () => {
  return (
    <div className="row contactus">
      <div className="col-md-5 contact-img">
        <img src={about_img} alt='customer support' style={{ width: "100%" }} />
      </div>
      <div className="col-md-6">
        <h1 className="bg-dark p-2 text-white text-center">ABOUT US</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui.Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo nisi possimus dolor facere enim maxime error laudantium accusamus, ea alias porro labore consequuntur minima maiores vero vitae architecto aspernatur qui
        </p>
      </div>
    </div>
  )
}

export default About
